### ISSUE TITLE
Image not found using 'CFWebSdk'

### ISSUE THREAD

**Issue by UdhayaMariappan** [cashfree/ios-CFWebSDK#12]
Hi,
When i launch app it shows image not found error 'CFWebSdk' swift 5.0

xcode version:10.2.1
swift version : 5
device : iPhone xr
phone OS version : 12.3.1
Project language : objective - c 
<img width="1186" alt="Screenshot 2019-06-18 at 1 42 36 PM" src="https://user-images.githubusercontent.com/28531437/59664595-fb7bdd00-91ce-11e9-8fb3-2baf2749a2fd.png">

**Comment by amitkarn** [comment]
Hi @UdhayaMariappan I solved this issue as follows:
1) Go to **General** tab and then to **Embedded Binaries** field
2) Add cashfree webSDK framework
