### ISSUE TITLE
Could not find module 'CFWebSDK' for architecture 'x86_64'; found: arm64, arm

### ISSUE THREAD

**Issue by varun-naharia** [cashfree/ios-CFWebSDK#15]
I am running code xocde 10.2.1 Simulator and getting this error

**Comment by prakharbhardwaj** [comment]
CFWebSDK framework doesn’t not support simulator architecture, try running it on physical device.

**Comment by varun-naharia** [comment]
Yes, but why it not supported  ?

**Comment by prakharbhardwaj** [comment]
> Yes, but why it not supported ?
@varun-naharia 
Because for the iOS Simulator, it uses your nested macOS environment i386 x86_64 architecture.
For more information, you can read **Multi-Architecture Build** topic.
