### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by prakharbhardwaj** [cashfree/ios-CFWebSDK#16]
Xcode 11 gives the following error:
`Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/PrakharBhardwaj/Desktop/Bono/bono-ios/CFWebSdk.framework/Modules/CFWebSdk.swiftmodule/arm64.swiftmodule`

**Comment by sharathfantain** [comment]
Facing the same issue... Can you please give the latest SDK asap...

**Comment by prakharbhardwaj** [comment]
> Facing the same issue... Can you please give the latest SDK asap...

@sharathfantain download the framework for Swift version 5.1 from the below links.

[iphone](https://drive.google.com/open?id=19Ixn4UQPx2CzCPCK7zyP3viT3_6Jf9RR)
[Simulator](https://drive.google.com/open?id=1BWtXCAuCEUCwc_4Ow-Di7r1jYdTIEzjq)
