### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler

### ISSUE THREAD

**Issue by losernobody** [cashfree/ios-CFWebSDK#18]
Xcode 12.2.1 gives the following error
`Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler`

**Comment by chintanMaisuriya** [comment]
> Xcode 12.2.1 gives the following error
> `Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler`

I'm also facing the same issue. Do you get any solution about this?

**Comment by losernobody** [comment]
No, I did not find any solution.

**Comment by zhao520wei** [comment]
XCode 11.2.1, error :  
Could not find module 'CFSDK' for target 'arm64-apple-ios'; found: i386, x86_64-apple-ios-simulator, x86_64, i386-apple-ios-simulator

**Comment by arjun-cashfree** [comment]
Please download the latest SDK and contact techsupport@cashfree.com for further assistance.
