### ISSUE TITLE
Could not find module 'CFSDK' for target 'arm64-apple-ios'; found: i386, x86_64-apple-ios-simulator, x86_64, i386-apple-ios-simulator

### ISSUE THREAD

**Issue by zhao520wei** [cashfree/ios-CFWebSDK#19]
XCode 11.2.1, error :
Could not find module 'CFSDK' for target 'arm64-apple-ios'; found: i386, x86_64-apple-ios-simulator, x86_64, i386-apple-ios-simulator

**Comment by zhao520wei** [comment]
when I import 4.2 swift CFSDK ,  
build , error:
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.2 compiler:

**Comment by arjun-cashfree** [comment]
Contact techsupport@cashfree.com for further assistance.
