### ISSUE TITLE
Invalid token sent in request

### ISSUE THREAD

**Issue by Neeraj204** [cashfree/ios-CFWebSDK#20]
While trying it on simulator after so many failed attempt of so much error, finally running successfully. Now I am getting error like 

> Invalid token sent in request

I am generating token from backend.
`{
    data =     {
        cftoken = "n49JCN4MzUIJiOicGbhJCLiQ1VKJiOiAXe0Jye.7l0nI4IDO2kDOmZDOxETZ1IiOiQHbhN3XiwCO2kDO5cDM4UTM6ICc4VmIsICMwUjI6ICduV3btFkclRmcvJCLiEDMwADSiojIklkclRmcvJye.BuGKU9hFd_74d9MHAv7tsx2HncWlEaDpx0AhSL3p0WToHrBg-aI866LLhv3tLg9EjB";
        message = "Token generated";
        status = OK;
    };
    status = 100;
}`

Then using following code I am initiating SDK:

`func initiateCFSDK() {
        let cashfreeVC = CFViewController(params: getPaymentParams(), appId: self.appId, env: self.environmentCF, callBack: self)
        self.navigationController?.pushViewController(cashfreeVC, animated: true)
    }`

It opens blank white page and following prints on log:

`<html><body onload='document.order.submit()'><form name='order' action='https://test.cashfree.com/billpay/checkout/post/submit' method='post'><input type='hidden' name='appId' value='109301ec5c3b5d3cdae83bf4203901'><input type='hidden' name='orderAmount' value='1'/><input type='hidden' name='customerPhone' value='9012341234'/><input type='hidden' name='tokenData' value='n49JCN4MzUIJiOicGbhJCLiQ1VKJiOiAXe0Jye.7l0nI4IDO2kDOmZDOxETZ1IiOiQHbhN3XiwCO2kDO5cDM4UTM6ICc4VmIsICMwUjI6ICduV3btFkclRmcvJCLiEDMwADSiojIklkclRmcvJye.BuGKU9hFd_74d9MHAv7tsx2HncWlEaDpx0AhSL3p0WToHrBg-aI866LLhv3tLg9EjB'/><input type='hidden' name='customerName' value='Test'/><input type='hidden' name='orderNote' value='Order Note'/><input type='hidden' name='orderId' value='Order121'/><input type='hidden' name='customerEmail' value='neerajnj.gems@gmail.com'/><input type='hidden' name='notifyUrl' value='https://test.gocashfree.com/notify'/><input type='hidden' name='orderCurrency' value='INR'/><input type='hidden' name='source' value='iossdk'/></form></body></html>
Finished navigating to url Optional(about:blank)
https
Finished navigating to url Optional(https://test.cashfree.com/billpay/checkout/post/submit)`

And in result handler showing error like this:

`JSON value : {"orderId":"","referenceId":"","orderAmount":"","txMsg":"Invalid token sent in request","txTime":"","txStatus":"FAILED","paymentMode":"","signature":""}

Result(orderId: "", referenceId: "", orderAmount: "", txStatus: "FAILED", txMsg: "Invalid token sent in request", txTime: "", paymentMode: "", signature: "")`

Anyone here to solve this issue?

**Comment by arjun-cashfree** [comment]
The SDK is hitting the TEST environment. Please ensure that the token is generated for the test environment instead of PROD. Contact techsupport@cashfree.com for further assistance. Closing this ticket as it is not an SDK issue.

**Comment by Neeraj204** [comment]
Token is also generated for the **TEST** environment.

**Comment by Neeraj204** [comment]
both have the TEST environment

**Comment by rward27** [comment]
facing same issue
