### ISSUE TITLE
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3 compiler

### ISSUE THREAD

**Issue by vmanot** [cashfree/ios-CFWebSDK#21]
Cashfree's iOS SDK is built without **Build Libraries for Distribution** set to **Yes**, and thus does not feature Swift module stability.

This prevents the SDK from being used by the future versions of Xcode, and is currently preventing me from using it with Xcode 11.3 (App Store).

Please refer to [this StackOverflow post](https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler) for the fix.

**Comment by arjun-cashfree** [comment]
This has been fixed. Please download the updated SDK.
