### ISSUE TITLE
How can I run Cash free sdk in Xcode 11?

### ISSUE THREAD

**Issue by LetsNurtureGit** [cashfree/ios-CFWebSDK#24]
Hello,

I have an issue with cash free sdk. I have xcode 11 and it's not running project because of your sdk is build of in xcode 10. 

Now I have warning Like  attached screen shot.so I have upgrade xcode 11 and not running my project because framework compiled in xcode 10. So please help me for that.

<img width="682" alt="Screenshot 2020-03-07 at 8 14 13 PM" src="https://user-images.githubusercontent.com/3041533/76380350-8cf03800-6378-11ea-86ed-eb7f508f821a.png">

**Comment by arjun-cashfree** [comment]
Please use the CFSDK.xcframework from this repository. You must be using the CFSDK.framework file mentioned in our Docs. We are in middle of revamping our docs so it has not been updated in a while. Please reach out to us at techsupport@cashfree.com if you need further help.
