### ISSUE TITLE
No Back Button: Cant go back from the web checkout form

### ISSUE THREAD

**Issue by meeraRchillar** [cashfree/ios-CFWebSDK#25]
Hi there,

I have integrated Cashfree successfully in my project . Everything works fine except this issue..'back button is not showing up' . 
In my project the method 
                 let cfViewController = CFViewController (
                        params: self!.getPaymentParams(),
                        appId: self!.appId,
                        env: self!.environment,
                        callBack: self!)
                    self?.navigationController?.pushViewController (cfViewController, animated: true);

is called inside the 'didSelectRowAt' method of TableView. Please help with the issue.. is that something I missed?

**I have added Cashfree in a simple sample app embedding my controller in UINavigation controller and then back button showed up.**

**Comment by arjun-cashfree** [comment]
When integrating our iOS SDK, the invoking UIViewController should be embedded inside a UINavigationController. The UINavigationBar is part of the UINavigationController and can be manipulated from any UIViewController inside the navigation stack.
Reach out to us at techsupport@cashfree.com for further assistance.

**Comment by meeraRchillar** [comment]
Hi,
Thanks for the reply.
Yes, we did a sample app for cashfree integration by adding
UINavigationcontroller in storyboard and everything went fine.
The problem is we have added UINavigationController programmatically for
our real project in the AppDelegate file. But the back button is not seen.
Do we have the provision to customize the CFViewController
modalpresentationstyle? Or is there any other point you can highlight on
this.. please let me know.

Thanks ahead
Meera
