### ISSUE TITLE
Error while uploading to appstore

### ISSUE THREAD

**Issue by Neeraj204** [cashfree/ios-CFWebSDK#26]
Please see the following screenshot and provide solution as I am in stage of to go live

<img width="1440" alt="Screenshot 2020-04-16 at 11 00 38 PM" src="https://user-images.githubusercontent.com/20571562/79489044-54f3a900-8038-11ea-8141-75af6b192ad5.png">

**Comment by arjun-cashfree** [comment]
Please use the .xcframework file instead of .framework file you are using in your project. You can find it at the root folder of this repo. The .framework file you are using does not have the binaries for physical devices. Reach out to us at techsupport@cashfree.com if you need further help with the integration.

**Comment by Neeraj204** [comment]
Ok. I am using .xcframework but for now when I upload my app using Xcode 11 it gives me following error:

Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.3

**Comment by Neeraj204** [comment]
And if I run using xcode 10.3 it is running but crashing the app as soon as it launches.

```
dyld: Library not loaded: @rpath/CFSDK.framework/CFSDK
  Referenced from: /private/var/containers/Bundle/Application/7B7E03D2-CFC0-4DA4-84F9-EDB4D4E906A4/PharmEarth.app/PharmEarth
  Reason: image not found
```

**Comment by arjun-cashfree** [comment]
Your project is still using the .framework file. Xcframework will only work
with xcode 11.+ And it is compatible with all Swift 5.+ Versions.

**Comment by vipinsaini0** [comment]
Im using Xcframework  with xcode 11+ and Swift 5+, still Im getting below error and if I removed this framework everything working fine.
see this screenshot - https://prnt.sc/ujhfus

I have to target and its working in one target and not working in another target, I made same setting in both the target.

**Comment by arjun-cashfree** [comment]
I think you have imported the SDK incorrectly.  Xcframeworks contain the binaries for architectures of the mobile devices (phones/iPads) and the desktops as separate .framework folders (inside) and Xcode chooses which one to use based on the target that is selected. 

This removes the need to run a post-build script that removes the unnecessary binaries from the release archive (if you use a fat framework) as the Xcode knows which .framework to use. 

Please reach out to techsupport@cashfree.com and we'll help you out in figuring out the issue.
