### ISSUE TITLE
Library not loaded on device iOS 13.6

### ISSUE THREAD

**Issue by Neeraj204** [cashfree/ios-CFWebSDK#28]
dyld: Library not loaded: @rpath/CFSDK.framework/CFSDK
  Referenced from: /private/var/containers/Bundle/Application/129C84C3-5919-4D9D-A307-3F3FBAAC7EE9/appname.app/appname
  Reason: image not found

**Comment by arjun-cashfree** [comment]
Neeraj,

Please use the CFSDK.xcframework file from this repo. We can see that you are using CFSDK.framework. If you are still facing issue, please contact techsupport@cashfree.com and we'll help you with the integration.
