### ISSUE TITLE
Class file is unavailable

### ISSUE THREAD

**Issue by rp9994** [cashfree/ios-CFWebSDK#5]
'SeamlessProVC' is unavailable: cannot find Swift declaration for this class

This error occur in given demo project. Please update the repository.

**Comment by basilcf** [comment]
Hi,

Are you running the SDK on physical iOS device ? 
Please retry using the latest [Swift 5 sdk](https://github.com/cashfree/ios-CFWebSDK/blob/master/CFWebSdk-BitcodeEnabled-Swift5.zip) on Xcode 10.2. 

Let us know if you're still facing the issue.
