### ISSUE TITLE
Could not find module 'CFWebSdk' for architecture 'arm64'; found: arm

### ISSUE THREAD

**Issue by mf-jay96** [cashfree/ios-CFWebSDK#8]
Getting this error:
Could not find module 'CFWebSdk' for architecture 'arm64'; found: arm

**Comment by chintanTBI** [comment]
Getting the same error while adding framework in project created with XCode_10.2.1

**Comment by basilcf** [comment]
Hi,

Please try running the Swift 5 sdk on Xcode 10.2

Please let us know by emailing us at techsupport@cashfree.com if you're facing any issues with the integration.

Best Regards,
Basil

**Comment by chintanTBI** [comment]
Okay. Thanks. I'll use Swift 5 sdk for that.
